### PR TITLE
magnified graph

### PR DESCRIPTION
**Pull request by mike-s123**
This changes the main screen graph to only show temps +- 20C from the setpoint. It uses 100 bytes more RAM (changed plotData to uint16_t, for 1 degree accuracy).  Makes the PID behavior more visible.  I could go back to a uint8_t with a +-40C range.

The old graphing is still there (modified for the change in plotData), there's a "magnify" boolean to control the graphing - future direction, perhaps add a choice, or cycle through both when quick pressing on main screen.

### CODE REVIEW

**Comment by deividAlfa** [comment]
I didn't see your code yet, but why use uint16_t when there's only 40ºC variation?
What precision are you talking about? The graph uses 40pixel height, so it can do +-20ºC with full precision.
My idea was to do this by doing this:
if ((currentTemp-20)<=setpoint) : set plot to 1 (first pixel only, botton line)
else if ((currentTemp+20)>=setpoint): set plot to 40 (full graph height)
else if (currentTemp>setpoint): plot=currentTemp - setpoint
else if (currentTemp<setpoint): plot=setpoint - currentTemp

**Comment by deividAlfa** [comment]
Hmm. I see the extra RAM a bit wasteful.
Whats the use of storing temps below 180ºC or over 500º, when your are going to limit the values anyways to fit the graph?

**Comment by mike-s123** [comment]
Odd, I got an email with your (first) comment, but I click on the link to come back here, and it's not here. And while I'm here, your second comment shows up. Whatever.

Anyway, I'm tracking actual temperature (1C resolution) toward the top of main_screen_draw, then doing all the scaling in the plotDraw condition. It didn't makes sense (and would be a lot of code/work) to dynamically scale the collection based on the current set temp.

But yes, I can collect it in 250-505 range, and go back to uint8_t. I was trying to cover the whole 180-500 range.

I was also thinking of making it non-linear - maybe the "inner" +- 10 pixels = 1C, and the "outer" 10 pixels 2 or 4C. That would show a wider range, +- 30 or 50. But there'd be a definite "knee." Exponential would be better, but that's a lot of floating point math.

**Comment by deividAlfa** [comment]
Yep, I send the comment without actually realizing the code... you know hehe....El 12 feb. 2021 0:41, Mike Sauve <notifications@github.com> escribió:
Odd, I got an email with your (first) comment, but I click on the link to come back here, and it's not here. And while I'm here, your second comment shows up. Whatever.
Anyway, I'm tracking actual temperature (1C resolution) toward the top of main_screen_draw, then doing all the scaling in the plotDraw condition. It didn't makes sense (and would be a lot of code/work) to dynamically scale the collection based on the current set temp.
But yes, I can collect it in 250-505 range, and go back to uint8_t. I was trying to cover the whole 180-500 range.
I was also thinking of making it non-linear - maybe the "inner" +- 10 pixels = 1C, and the "outer" 10 pixels 2 or 4C. That would show a wider range, +- 30 or 50. But there'd be a definite "knee." Exponential would be better, but that's a lot of floating point math.

**Pull request merged**
