### PR TITLE
Update u8g2 fonts

### PR DESCRIPTION
**Pull request by sst311212**
I also noticed F072 firmware build failed because flash run out.

### CODE REVIEW

**Comment by deividAlfa** [comment]
Sorry, functionality goes first, I will revert the previous PR.
I think it's better you and/or @sst311212 make your own fork for chinese language!

**Comment by sst311212** [comment]
OK, so even traditional chinese will be canceled?

**Comment by deividAlfa** [comment]
Given the complexity and space requirements, plus I will not maintain chinese stuff as I have zero knowledge, I think it would be better to make a fork specifically for Chinese and link to it from the main project.
I mean, removing all languages except english and Chinese.

Don't delete it, I might make a special release for chinese only.

I know F072 is a minority... Maybe disable chinese for that version.

**Comment by sst311212** [comment]
Maybe it can add new build profile for chinese version and use some defined variables to control building behavior?

I already tested, it should be good.  https://github.com/sst311212/stm32_soldering_iron_controller/commit/d8ff39cdda38ab6d06be4fbdd5b7c6ba12290884

**Pull request closed without merging**
