### PR TITLE
README.md - 'Housekeeping'

### PR DESCRIPTION
**Pull request by dreamcat4**
This is the housekeeping request:

(1) Add the [`Changelog.md`](https://github.com/dreamcat4/stm32_soldering_iron_controller/blob/master/Changelog.md) file. It was your changes.txt attachement on eevblog.

Why?

* Because I find it's easier to learn / understand your code, by exploring from your Changelog notes.
* Also because you took the time to write / document those past history, it's really useful to me! Thanks.

(2) Switch to single `master` branch.

Why?

* Because feature branches are only really meant for experimental development, before rolling them back into `master` branch. That is the best worklflow. We have now figured out this branch should be 'mainline'. So time to roll it back into master.

**Note:** This merge request is raised on your current development branch named [`Quicko_T12_stm32f072c8`](https://github.com/deividAlfa/stm32_soldering_iron_controller/tree/Quicko_T12_stm32f072c8). So in order to do this merge, you will need to create a new branch named `master`. And then switch to that branch. Then merge this / take this.

It's also important to switch your default branch back to master in github repository settings. Under 'branches' tab. And set it back to `master`. After pushing up a new master branch that has been merged.

Hopefully you will be able to do this in git now. It's more advanced operations. More complicated I know.

*End PR*
===

#### Other commentary

It is also going to be necessary to figure out a good strategy for maintaining multiple hardware configurations. As we already were discussing over on eevblog. A solution for that other problem (code generation + libs), such solution will eventually require merging your other branch. Later on. So all the following discussion is not a part of this merge request.

But for the moment I suggest keeping that branch just as it is. Until we can merge it back later on. Not to do too many things at once.

Looking at what you have done here...

https://github.com/deividAlfa/stm32_soldering_iron_controller/compare/Quicko_T12_stm32f072c8...deividAlfa:KSGER_v1.5_stm32f103c8

It seems like you are pulling in and versioning all the ST libraries. And mostly these 4 commit are adding new files. That don't exist on the other branch for the 072. Therefore there really is not actually very much conflict, when the different sets of library files have different filenames to each other. Or they are in their own seperate subfolder (STM32F1xx). This does not require a seperate branch. And the size of repository is the same regardless.

Another point I should be saying here: is that versioning the ST libs (at all) is both good and a bad thing. On the positive side it makes it easier for downloading and compiling. Not to require to fetch libs. Everything included.  However the drawback is that we are versioning many files that we do not need to. If they can be automatically downloaded as a part of the build process. This is what the ST CubeIDE, and also the PlatformIO (both) does this operation, automatically. Of course the benefit of relying on those "download" libraries feature... is not needing to keep track of hundreds of files. IDK. So while I'm not entirely sold or dismissive either way it does not mean we need to keep seperate branches (for that aspect).

Later on, we should merge this `KSGER_v1.5_stm32f103c8` branch and roll it back onto master branch. But that would be a seperate PR. Not yet.

I think it's easy to see the branching feature of github and believe that is the right solution to this problem - it isn't. It will just generate a lot of pointless work (more housekeeping). Which then reduces the amount of developer time (for coding!). Which is a lot more fun. Trust me. I have seen this / done this before. It's a nightmare. Repeating everything all the time... Boring as hell. I don't wish to be a part of that.

### CODE REVIEW

**Comment by deividAlfa** [comment]
Yep, there's a lot to do. That was just some playing from my side trying to learn git.
About the ST libraries, yes, you're right. I could add them to git ignore.
About the different cube projects, we'll see how... Maybe just a folder for each hardware with the project, cubeMX files and a base header file that defines the board.

**Comment by dreamcat4** [comment]
Cool man. Looking forwards to it!

**Comment by dreamcat4** [comment]
@deividAlfa  you didn't merge these minor README changes, but why not? What was the reason for that decision?

**Comment by deividAlfa** [comment]
Oops, my bad. Git newbie here!

**Comment by dreamcat4** [comment]
Well @deividAlfa there are a whole bunch of different ways to deal with Pull Requests from other people.

It's really a subjective thing, especially on a case by case basis. If you are (like me), you will probably have greater trouble handling code contributions when you yourself are already ahead with a lot of working changes. That have not been published yet. It can be difficult. Some people love merging stuff all the time. Other people hate doing it.

Heres a simple rundown of possible strategies, for handling PRs:

* You might decide to develop a policy of asking people to open an issue for discussion first. Before they spend the time / effort to work on and submit a new PR.

This can be helpful because it gives you an opportunity to shape the way other people are making their contributions. And to both encourage people to do things in the right way, and also let them know (for example) if you cannot accept a feature for the timing is bad, or it's just not going to fit well with the other existing ongoing work.

If that is a good idea then it is something to write into the contributions guidelines. With some clear bullet points, that other developers should read / follow. Before they waste time working on improvements that ultimately might not be possible to merge.

* You might decide to respond to a PR by asking for certain additional changes or corrections. That they must go back and add in themselves, if it is not up to scratch. The inline code comments feature is very useful mechnism for doing that. If it is more easy to suggest as specific feedback, how they can make further improvements. This is considered to be a more traditional style of peer 'code review' etc. But it only works well, if you happen think that by telling the submitter to make those amendments is... actually the best way to get them to make better contributions, encourage participation etc. But sometimes that is just a big hassle, because it's difficult to communicate those finer technical points in a way that is simple and time effecient.

* You might decide it's actually much easier for you to make the necessary amendments yourself. Either during the middle of git merge process. Or immediately after merging. This can be better especially when it would be harder to communicate all the changes so efficiently to the other guy. And then just simply let them know what you had to change, in order to accept their contribution.

* Finally you might just want to completely ignore, or 'ghost' a PR. And leave it open indefinitely. There's absolutely nothing wrong with doing that either! Because sometimes we don't have the time to do it justice, or simply 'don't know' (at least, initially) what would be the best thing to do. 

Then much later on, and with the benefit of hindsight. You might come back to that PR... and it might make a lot more sense! Perhaps years later! And by that time, the problem itself might have already ended up getting solved anyhow. Or the matter is since become irrelevent / doesn't matter anymore!

It's important I think to understand that leaving issues and PRs open is totally fine. Nobody is watching your performance here on Github! It's all for fun. And leaving an issue open is often more permissive and a better choice than trying to immediately and actively close issues. Just for the sake of the statistics. Or inbox zero philosophy. Because closing an issue (or pr, whatever) 'too soon', it can discourage participation, and dampens community involvement.

None of these specific approaches is actually right or wrong. In fact they are all perfectly valid choices and mostly just depends each time. For which solution is best fit for that specific situation... also accounting for your own development work. And where things are sitting at the time.

I do encourage you (as a lead developer) to keep options open for 3rd party contributions in the future. Perhaps not so much right now, (when you are so bust at the moment, and achieving so much), but thinking forwards once you have eventually done most of the things you wanted. When the code eventually becomes more stable. And not so many drastic changes anymore.

Thanks again! Hope you didn't mind my tips / suggestions! And look forwards to talking over on the eevblog forums. Will go back to fixing my own board now. As it requires new mosfet, etc.

**Comment by deividAlfa** [comment]
Don't get it too serious! All I do wrong is due ignorance... I'm no used to github, so pull requests and other stuff are totally new to me, I don't really know what they are, slowly learning everything... At first I thought it was a question system!!
The git won't be updated too much until I start shaping the firmware into something I find close to the real thing... I don't feel confident uploading anything, I could mess things up and ending losing the code.
So for now, I develop using a local git... when I make a big step forward and everything works, I copy the code to the other project and upload to git.
The other branches are more like a backup and test system. I have the basic done to work on other hardware, and as I can't test it, I also don't want to merge it into the final code. The firmware features are not important on these, only the hardware layer.
If someone tries it and everything works (oled, adc, buttons, etc...) then I will attempt to unify the code for the different hardwares.

I do this because when I accidentally make a bad commit, I haven't found how to reverse that in a clean way.
If I commited something and want to revert it back, instead of deleting the commit, it adds another on top indicating that the last commit was deleted. I don't want such behaviour, it's ok if we roll back but still want to keep the commit for othe purposes, but when  there was silly mistake, that commit wil just add junk.
That's why I keep a local git for everyday work, when I usually add a new feature, also do appear 10 new bugs lol.
Imagine the git commit messages, "forgot a '='", "Added a & here". "Removed the '&'". So in the end you'll have 100000 messages making the tracking of the code very tedious.

Should I add a 'test' branch for the everyday work?

As I say I'm new here. I don't think I'm a leader of anything, more like a contributor.
You're welcome and everybody who want to participate.

**Comment by dreamcat4** [comment]
> Should I add a 'test' branch for the everyday work?

The simple answer: No.
(because that makes an branch to manage, but without very much benefit).

Best practice is:

* To have only 1 ongoing development branch, `master`.
* To make stable points, using `git tag`. To mark those stable commits along the line.
* Only ever make separate branches for "feature branches". Which are intended only ever for merging back into the mainline tree. (usually 1 feature branch --> becomes 1 PR). Once the changes are merged, then the "feature branch" can be deleted and removed. Because all the code has been incorporated into the main line of development. Or otherwise (if not merged), then abandoned / rejected.

So what to do then?

Here is a very good alternative solution. Something else we can do instead. This method is being used by the lead developer for zfs... who is a very busy person any makes many risky changes very often. And has very little time. Therefore, this type of workflow has proven to be most efficient, and safe:

1* Push your changes to your own personal repo, publicly on `master` banch and keep them in sync with your local working files. Commit very often.
2* But also we must create an *organization* account on github too. With the same name as the project repo name. For example `stm32_soldering_iron_controller/stm32_soldering_iron_controller`. Or whatever name seems best for the `org` name and `repo` name. IDK.
3* Then the other organization account...  becomes the place for all merge requests, the issue tracker, etc. and not the personal account.

OK... so then what is the publishing workflow?

* We have accumulated many unstable changes into the personal repo. And have been pushing them all up on github, as `username/repo:master`.
* Once you have reached a known stable code point. Then it's already been uploaded into your `master` branch, right? OK then:
* Push your `username/repo:master` changes --> to the organization account.
* Also create a checkpoint for the update.
* Use the `git tag` command.
* This will also create a new point release on github. Automatically.
* A release on github, based from the name of the git tag. If you have `.hex` binary files, those build products can also be uploaded and attached to the release. It is a very quick and simple process. Without too much burden / overhead.

OK then what is the user workflow?

* People can either download the latest commit of `org/master` branch. Or download a fixed release version, for the precompiled .hex, etc. If that was also uploaded on to the github "releases" page.
* This then means nothing in the `org/repo` account is too experimental or unstable. It is relatively stable code. So there is no risk to other people.

What else important, to learn about git?

* We should stage HUNKS within a file. Collecting and gathering fragments. So you can group together a change set into a single commit, only for those set of changes which belong together.

Even if the change is scattered across multiple files. Maybe you still have other changes not finished. Other stuff left to commit, and are not finished yet. But those other changes are not related. The Staging of HUNKS is the feature which solves this problem.

A good GUI program is very important,  for staging HUNKs. If you don't have a good program, then staging HUNKs will be very slow. But we need to do that task very often.... GUI is what makes it possible. For example I use SmartGit.

What else?

* This approach encourages to actually make git commits more often... that is good, right?
* You now can use your own personal master branch more recklessly. Which is good! And without worrying that a person will download your unfinished code and use it when it isn't ready yet. However the code will still be backed up in github. And possible for others to see.
* This encourages changelog notes directly into git as the commit message. This is a more efficient way to work. And then makes it *much easier* to understand the code changes when they are entered into the git log. Otherwise there is a disconnect and the commit is difficult to understand.
* It is OKAY to make many small commits, for typos, formatting, etc. All in between real and more important code changes. That is fine! It does not reflect bad, or get in the way of anything.

In fact it's better! Because then we can ignore those commits, and they do not get in the way anymore of doing `diff`s. This is a good thing! Otherwise it's impossible to separate in those commits from the actual changes we want to check / compare in our trees.

If you adapt your approach to git, then it will help you to stay in sync with git. This is important because once changes gets too far away, it becomes a lot harder to reconcile and push updates. Which is then put off longer, etc. I know this! (from another open source project). It's a very common experience.

Hopefully with these suggestions, you can find git more useful. To improve the efficiency of git workflow and spend less % time actually in git. Because that time overheads is lost for coding.

**Pull request merged**
