### PR TITLE
Big step increments

### PR DESCRIPTION
**Pull request by abourramouss**
Added big step increments as ygi user suggested in the eevblog forum.

You can also select the big step increment in the menu

### CODE REVIEW

**Review by abourramouss — COMMENTED** [review]
Changed "Big step" to " Big step" with indentation

**Comment by deividAlfa** [comment]
Nice work.
You need to make a new widget pointer for bigstep, not use the same like you're doing.

At the start of system_screen.c

static editable_widget_t *editable_system_bigTempStep;


Then in the widget setup:

editable_system_bigTempStep=edit;


Check system_onEnter where the widget temperature unit is updated (F or C), duplicate these 2 lines using the correct name for the pointer.

**Comment by abourramouss** [comment]
End strings were added as requested, that's why it wasn't showing the correct temperature string at the end.
Thanks.

**Review by deividAlfa — APPROVED** [review]

**Comment by deividAlfa** [comment]
Merged

**Pull request merged**
