### PR TITLE
Update gui_strings.c

### PR DESCRIPTION
**Pull request by srkn73**
I added Turkish characters but it doesn't show
I'll fix the long ones as I use the device

### CODE REVIEW

**Comment by deividAlfa** [comment]
I need to know exactly the characters you need.
I added the ones you said, but I don't know tukish, you forgot to mention "İ" and "ı".
What else do need to be added? It takes a lot of work, please check it properly 👍

**Comment by srkn73** [comment]
hi 
missing characters (  İ ı )
i am a beginner at this job :(

**Comment by deividAlfa** [comment]
Done. Can you compile it yourself? I cannot make builds for every test.

**Comment by srkn73** [comment]
thank you
works perfectly 👍

I hope you make software in this device
device is good but software is very bad  :)
https://tr.aliexpress.com/item/1005002990456435.html?spm=a2g0s.9042311.0.0.645a4c4dCiOrOz

I wish you success in your work

**Comment by deividAlfa** [comment]
I don't have that device, so I can't do anything...

**Pull request merged**
