### PR TITLE
Fast-slow encoder rotation increments

### PR DESCRIPTION
**Pull request by abourramouss**
As the eevblog user "ygi" suggested, this is a pull request to add the fast-slow temperature increments.

### CODE REVIEW

**Comment by abourramouss** [comment]
Don't merge yet please, I made an error testing this build.

NUM_DIFF was too low, so it didn't detect the fast rotation of the encoder.

**Comment by abourramouss** [comment]
Ready to merge, please review/test before merging.

Time_diff value might be too low or too high, in KSGER t12 v3 it's good. If it's too sensitive, increase it. I left it at 57

**Comment by abourramouss** [comment]
Changed time_diff to 80 again.

**Comment by deividAlfa** [comment]
Ensure to test it properly! Will wait a bit more...

**Comment by abourramouss** [comment]
> Ensure to test it properly! Will wait a bit more...

Sure, thanks.

**Comment by abourramouss** [comment]
As you added better support for it, pr will be closed.

**Pull request closed without merging**
