### PR TITLE
Add simplified Chinese language display

### PR DESCRIPTION
**Pull request by Hifly-rc**
Add simplified Chinese language on the basis of existing traditional Chinese language. The compilation flash memory only increases 2KB, and optimization the Chinese language library generates script
I will follow the main line of the main line of the code update of the main line of the main line
QQ截图20240331144409

### CODE REVIEW

**Comment by deividAlfa** [comment]
Do we really need two chinese versions?
Why did you disable debug screen?
These files shouldn't be modified:
.gitignore, Building_script.bat, main.h, main.c

**Comment by Hifly-rc** [comment]
Thank you for your response, the Debug switch has forgotten to recover. Can you pass this modification except for this? There is a difference between simplified and traditional glyphs. Although most of them are the same shape, they look less adaptable.

**Comment by deividAlfa** [comment]
@sst311212 could you please check if this PR breaks any of your stuff?

**Comment by Hifly-rc** [comment]
> @sst311212 could you please check if this PR breaks any of your stuff?

The original font library generation script is a bit troublesome for Simplified Chinese. Now, we can directly extract all Simplified and Traditional characters from the gui_strings.c file and remove duplicates, which can simplify the generation process. It would be even better if we could integrate the font pixel modification code with the u8g2 fonts. c content into the script in the future

**Comment by sst311212** [comment]
**Sorry David, but use chinese to communicate with Hifly-rc should much easier.**

> The original font library generation script is a bit troublesome for Simplified Chinese. Now, we can directly extract all Simplified and Traditional characters from the gui_strings.c file and remove duplicates, which can simplify the generation process. It would be even better if we could integrate the font pixel modification code with the u8g2 fonts. c content into the script in the future

原本的 bdf 生成腳本難道不是只需要更新字庫(txt)裡的文字就能產生相應的索引(map)嗎？

然後自動抽字的想法很不錯，但是 menu 跟 small 需要用的字不太一樣
有些 small 的字放在 menu 裡面就是多餘的會浪費空間，那麼你該如何分辨要放到哪？

我自己是用 EmEditor 編輯字庫，去重&排序 應該是沒什麼問題才對
除了剛開始使用這個韌體還不太清楚選項的意思是什麼，翻譯還需要多次調整
不然字庫的文字不太需要去變更，除非 David 多加入了新功能進去

最後，個人認為自動抽字功能有點多餘
而且也不是很喜歡把所有腳本整合在一個 py 裡
然後先來後到，為什麼簡體是排在繁體前面？WHY？


> @sst311212 could you please check if this PR breaks any of your stuff?

I hadn't test yet, but if this generation script work with schinese, it should be fine with tchinese.
And I think this PR should squash into one commit or simplify commit history.

**Comment by Hifly-rc** [comment]
> **Sorry David, but use chinese to communicate with Hifly-rc should much easier.**
> 
> > The original font library generation script is a bit troublesome for Simplified Chinese. Now, we can directly extract all Simplified and Traditional characters from the gui_strings.c file and remove duplicates, which can simplify the generation process. It would be even better if we could integrate the font pixel modification code with the u8g2 fonts. c content into the script in the future
> 
> 原本的 bdf 生成腳本難道不是只需要更新字庫(txt)裡的文字就能產生相應的索引(map)嗎？
> 
> 然後自動抽字的想法很不錯，但是 menu 跟 small 需要用的字不太一樣 有些 small 的字放在 menu 裡面就是多餘的會浪費空間，那麼你該如何分辨要放到哪？
> 
> 我自己是用 EmEditor 編輯字庫，去重&排序 應該是沒什麼問題才對 除了剛開始使用這個韌體還不太清楚選項的意思是什麼，翻譯還需要多次調整 不然字庫的文字不太需要去變更，除非 David 多加入了新功能進去
> 
> 最後，個人認為自動抽字功能有點多餘 而且也不是很喜歡把所有腳本整合在一個 py 裡 然後先來後到，為什麼簡體是排在繁體前面？WHY？
> 
> > @sst311212 could you please check if this PR breaks any of your stuff?
> 
> I hadn't test yet, but if this generation script work with schinese, it should be fine with tchinese. And I think this PR should squash into one commit or simplify commit history.

我认为menu字集用其它工具生成很多余，自动抽取并排重方式显然更方便，small不需要改动所以没有对其做抽字处理，经过排重处理后跟menu重叠的字符非常少（你可以对比一下）。原来的font_menu_ch.txt文件用文本编辑器打开是一些乱码并不直观，我不明白之前用什么工具创建。
任何多语言电子产品语言排序都是按照这种规则切换，我觉得很合理。

**Comment by Hifly-rc** [comment]
Whether or not I can successfully merge this branch is not the focus for me. I work in the maintenance industry, and soldering iron is the tool I use the most frequently. It is rare to find an excellent open source project, and I will actively upgrade all soldering iron hardware to the current firmware. For this reason, I have specially designed a version of KSGER v3.0 similar controller, and I hope to share the CAM file of the controller with friends around me.
QQ截图20240402184030
QQ截图20240402184038
QQ截图20240402184239

**Comment by sst311212** [comment]
> 我认为menu字集用其它工具生成很多余，自动抽取并排重方式显然更方便，small不需要改动所以没有对其做抽字处理，经过排重处理后跟menu重叠的字符非常少（你可以对比一下）。原来的font_menu_ch.txt文件用文本编辑器打开是一些乱码并不直观，我不明白之前用什么工具创建。 任何多语言电子产品语言排序都是按照这种规则切换，我觉得很合理。

menu 跟 small 產生後的點陣字體不共用，可以的話還是盡量優化，減少占用體積
是用 EmEditor 編輯的，編碼格式是 UTF-16LE w/o BOM，py 裡面我是直接當 byte 讀取了

設計看起來不錯，另外你有發現在使用烙鐵時，晃動手柄觸發水銀開關會造成溫度讀值偏差的現象嗎？
我用 KSGER GX V2.1S 的控制板只要讓水銀開關導通，顯示的溫度讀值就會高出約5到10度C
DEBUG 模式下的 RAW 值大概會變高30~50，不確定是不是 KSGER 線路設計的問題，OPA 換了 AD8605 也是一樣

**Comment by Hifly-rc** [comment]
> > 我认为menu字集用其它工具生成很多余，自动抽取并排重方式显然更方便，small不需要改动所以没有对其做抽字处理，经过排重处理后跟menu重叠的字符非常少（你可以对比一下）。原来的font_menu_ch.txt文件用文本编辑器打开是一些乱码并不直观，我不明白之前用什么工具创建。 任何多语言电子产品语言排序都是按照这种规则切换，我觉得很合理。
> 
> menu 跟 small 產生後的點陣字體不共用，可以的話還是盡量優化，減少占用體積 是用 EmEditor 編輯的，編碼格式是 UTF-16LE w/o BOM，py 裡面我是直接當 byte 讀取了
> 
> 設計看起來不錯，另外你有發現在使用烙鐵時，晃動手柄觸發水銀開關會造成溫度讀值偏差的現象嗎？ 我用 KSGER GX V2.1S 的控制板只要讓水銀開關導通，顯示的溫度讀值就會高出約5到10度C DEBUG 模式下的 RAW 值大概會變高30~50，不確定是不是 KSGER 線路設計的問題，OPA 換了 AD8605 也是一樣

在测试的几个控制器上都没有出现过你所描述的BUG，的我认为可以从两个方面排查，1、断开手柄的振动开关信号线直接从控制器焊盘用镊子短路振动开关焊盘，2、示波器测量LDO前端24V与后端3.3V的纹波值是否过高。

I will close this PR first and wait for it to meet the merger requirements before resubmitting

**Comment by deividAlfa** [comment]
So what happened in the end? Where is this PR going?

**Comment by sst311212** [comment]
> 在测试的几个控制器上都没有出现过你所描述的BUG，的我认为可以从两个方面排查，1、断开手柄的振动开关信号线直接从控制器焊盘用镊子短路振动开关焊盘，2、示波器测量LDO前端24V与后端3.3V的纹波值是否过高。

我用不含震動開關的245手柄是正常的，只能推測是 S 訊號串回負極影響了 OPA 工作
手上沒有示波器可以測量訊號，個人只是偶爾焊接的普通玩家，換換滑鼠鍵盤什麼的小東西而已

> So what happened in the end? Where is this PR going?

I was discussed chinese font map file generating with him, so he might tweaking python code.

**Pull request closed without merging**
