### PR TITLE
Update TChinese translation

### PR DESCRIPTION
**Pull request by sst311212**
Can you make an option in menu to turn off temperature saving to avoid flash wear,
and use this option to determine using saved temp or default temp at system power up?

### CODE REVIEW

**Comment by deividAlfa** [comment]
Why? There's nothing to worry, the temperature storage area is only erased every 1K temperature changes, not for every change!
Also it's only stored after 10 seconds with no changes.

10K flash erase cycles * 1K, that's 10  million temperature changes!

It would take 3 years changing the temperature every 10 seconds non-stop.
For 100 temperature changes every day, it would take 274 years!

This has been thoroughly analyzed before implementation, it'll be fine!

With battery it's instantly stored for every change, as there's nothing to wear out, it's written to the rtc sram.

**Comment by sst311212** [comment]
Because my board's mcu is cks clone, I can't sure it has 10k erase cycles.
I currently use battery on mode, and turn off battery-loss error in source code.

**Comment by deividAlfa** [comment]
I wouldn't worry. What's the cost of a new stm32 anyways!

**Comment by sst311212** [comment]
New stm32 doesn't cost much, but I have to buy a hot air gun to replace chip...
I think buy a new backup controller board is much easier. lol
Anyway, thanks you keep adding new features.

**Comment by deividAlfa** [comment]
Even if it was only 1K erase cycles, it will last decades, it will erase the temperature flash area every 10 days changing the temperature 100 times a day!
Changing any other setting like tip or profile will instantly erase and store new settings, it's actually more harmful.
I'm still with my first stm32, and it has had a lot of flashing during  the developing of this firmware!

Seriously, no worries, it won't cause any harm.

**Comment by sst311212** [comment]
New controller board has arrived just in case the old one has damaged. 🤣
IMG_20231220_230913


I notice you said changing settings does more harmful than save temperature.
If use AB slot for settings saving will make mcu stand longer.
Adding a variable both in AB slot, and use 0|1 to do XOR, thus system can determine which slot is currently use.

**Comment by deividAlfa** [comment]
Don't think so much! It'll be fine! 
Maybe I'll add similar saving method for current tip/profile, but the other settings are not changed so much everyday.
Battery mod works great for me,

**Comment by sst311212** [comment]
David, setUserTemperature will force temp. not lower then min_temp, it make debug menu and calibration's zero_set malfunction.

**Comment by deividAlfa** [comment]
Aha, I'll fix that. In the future, please open issue for this things.

**Comment by deividAlfa** [comment]
Assigned [issues/77](https://github.com/deividAlfa/stm32_soldering_iron_controller/issues/77).
Fixed in 769cda886ad241717edd03618568f4af47cfab92.
New release: [v1.11.5](https://github.com/deividAlfa/stm32_soldering_iron_controller/releases/tag/v1.11.5)

**Comment by deividAlfa** [comment]
Sorry, my local repo was not updated, I accidentally overwrote your PR.
Please submit it again!

**Comment by sst311212** [comment]
Thanks 👍

**Pull request merged**
